# Generated by Django 6.0.2 on 2026-02-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
